version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
        - .env

    depends_on:
     - db
     - cache
    command: tail -f /dev/null


  db:
    image: mdillon/postgis:10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432'
    volumes:
      - ./.data/dbpgdata:/var/lib/postgresql/data

  cache:
      restart: always
      image: redis:4.0
      ports:
        - "6300:6379"

  flower:  
    image: mher/flower
    command: ["flower", "--broker=redis://cache:6379/0", "--port=8888"]  
    ports:  
      - 8888:8888
    depends_on:
     - db
     - cache